version: '3.9'
services:
  motorhead:
    image: ghcr.io/getmetal/motorhead:latest
    container_name: motorhead
    depends_on:
      - redis_stack
    environment:
      PORT: 8080
      REDIS_URL: redis://redis_stack:6379
    ports:
      - 8080:8080
  redis_stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - /srv/redis/:/data
