version: '3.9'
services:
  uptimekuma:
    image: louislam/uptime-kuma:latest
    container_name: uptimekuma
    ports:
      - 3001:3001
    volumes:
      - /home/user/volumes/uptimekuma:/app/data
    restart: 'unless-stopped'
