version: '3.9'
services:
  twingate:
    image: twingate/connector:1
    container_name: twingate-singing-hippo
    sysctls:
      - "net.ipv4.ping_group_range=0 2147483647"
    environment:
      TWINGATE_NETWORK: my-awesome-network
      TWINGATE_ACCESS_TOKEN: eyJhb...
      TWINGATE_REFRESH_TOKEN: KXX...
      TWINGATE_LABEL_HOSTNAME: "`hostname`"
    restart: unless-stopped
